root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
bin = "./tmp/main.exe"
include_ext = ["go", "toml", "env"]
exclude_dir = ["vendor", "tmp", "testdata"]
delay = 1000
stop_on_error = true

[color]
app = "magenta"
build = "yellow"
runner = "green"

[log]
time = true

[misc]
clean_on_exit = false

[runner]
pre_cmd = ["echo 'Rebuilding...'"]