version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: chatting_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatting_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: chatting_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./public/uploads:/app/public/uploads
    working_dir: /app

volumes:
  postgres_data:
